# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Windows-19

steps:
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean deploy'
    artifactoryResolverService: 'Artifactory'
    targetResolveReleaseRepo: 'maven-azure-libs-release'
    targetResolveSnapshotRepo: 'maven-azure-libs-snapshot'
    artifactoryDeployService: 'Artifactory'
    targetDeployReleaseRepo: 'maven-azure-libs-release-local'
    targetDeploySnapshotRepo: 'maven-azure-libs-snapshot-local'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    javaHomeOption: 'JDKVersion'
    
