
pool: 
  name: Default
steps:
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean deploy'
    artifactoryResolverService: 'Artifactory-Cloud'
    targetResolveReleaseRepo: 'maven-azure-libs-release'
    targetResolveSnapshotRepo: 'maven-azure-libs-snapshot'
    artifactoryDeployService: 'Artifactory-Cloud'
    targetDeployReleaseRepo: 'maven-azure-libs-release-local'
    targetDeploySnapshotRepo: 'maven-xray-libs-snapshot-local'
    javaHomeOption: 'JDKVersion'
  