trigger:
- main

pool:
  name: SumedhaPool

steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_HOME"
      echo "Java version:"
      java -version
    displayName: 'Install Java 17'

  - task: JFrogMaven@1
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean deploy'
      artifactoryResolverService: 'Artifactory-Cloud'
      targetResolveReleaseRepo: 'maven-azure-libs-release'
      targetResolveSnapshotRepo: 'maven-azure-libs-snapshot'
      artifactoryDeployService: 'Artifactory-Cloud'
      targetDeployReleaseRepo: 'maven-azure-libs-release-local'
      targetDeploySnapshotRepo: 'maven-azure-libs-snapshot-local'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      javaHomeOption: 'Path'
      jdkDirectory: '$(JAVA_HOME)'
